# Generated by Django 4.2.1 on 2023-06-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_scope_tag_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Основной'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
